# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8f648adf2bfdcc4c9973b97688e6ace03def4e907e4c595ec13320d80c35d54b1b2e535cc2702ca8555b59018d7a91ade3d33c1f93586499e14b32c0df42f93

test:
  secret_key_base: 03ff83cc9c12cf277478b9ded242d9d72dfbd8fea617c2d53a7cb373e279270f76d143a32a3403d4579563b30c0f206f243f28b7437edad2699a7ab882932fdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
